[tool.black]
line-length = 120
# Для надёжности оставим py311: black иногда отстаёт по поддержке py313.
# Если всё ок на твоей версии black, можно сменить на ["py313"].
target-version = ["py311"]

[tool.ruff]
line-length = 120
# ruff уже отлично понимает 3.13 — включаем.
target-version = "py313"
extend-exclude = ["ver1.5.py"]

[tool.ruff.lint]
# Базовый набор + то, что у тебя уже было
select = ["E","F","I","UP","B","SIM","W","PL"]
ignore = ["E203"]  # совместимость с black

[tool.ruff.lint.per-file-ignores]
"lite_upgrade.py" = ["PLR0915","PLR0912","PLR0911","PLR0913"]
"url_cutter.py"   = ["PLR0915"]

[tool.ruff.lint.isort]
# Чтобы isort (через ruff) относил твой модуль к first-party
known-first-party = ["url_cutter"]

[tool.setuptools.package-data]
urlcutter = ["assets/**/*"]

[tool.bumpversion]
current_version = "0.1.0"
commit = true
tag = true
